
import java.util.Objects;

class Laptop{
        String Model;
        int price;
        int serial ;
        // public String toString(){
        //     return "hey";
        // }
        public boolean equals(Laptop that){
            if(this.Model.equals(that.Model)&&this.price==that.price){// to objects are equals 
                return true;
            }
            else 
                return false;
        }

        // generated by ide right click select source action select generate equals and hashcode
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.Model);
        hash = 17 * hash + this.price;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Laptop other = (Laptop) obj;
        if (this.price != other.price) {
            return false;
        }
        return Objects.equals(this.Model, other.Model);
    }
    }

public class ObjectClass{
    public static void main(String[] args) {
        Laptop obj = new Laptop();
        obj.Model="Lenovo yoga";
        obj.price=110000;
        obj.serial =1122;
        System.out.println(obj);
        //hexadecimal value printing bcz default toString()
// for toString method it give coorrrect answer

         System.out.println(obj.toString());
         Laptop obj2=new Laptop();
         obj2.Model="Lenovo yoga";
         obj2.price=110000;
         obj2.serial=1133;
         boolean result=obj==obj2;
         System.out.println(result);//false
         boolean result1=obj.equals(obj2);
           System.out.println(result1);

    }
}